### ISSUE TITLE
Build fails on latest nightly

### ISSUE THREAD

**Issue by fhartwig** [carllerche/nix-rust#103]
https://github.com/rust-lang/rust/pull/24461 seems to have broken the build on nightly. The `impl`s generated by the`sockopt_impl` macro violate this. I'm trying to find a good way to fix this, but my macro-fu is pretty weak.

**Comment by posborne** [comment]
With the 2014-04-19 nightlies, I am also running into issues resulting from `::std::os::unix::io::Fd` changing to `::std::os::unix::io::RawFd`.  This change was introduced by https://github.com/rust-lang/rust/commit/6370f2978e485fd46bcb64f51a1c003395acfedc.

Here's the first error I hit with the fixes from @fhartwig:

```
src/sys/socket/sockopt.rs:7:5: 7:26 error: unresolved import `std::os::unix::io::Fd`. There is no `Fd` in `std::os::unix::io`
src/sys/socket/sockopt.rs:7 use std::os::unix::io::Fd;
                                ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by fhartwig** [comment]
@posborne Are you sure you're on the right branch? The commit you refer to was merged into rust master almost 3 weeks ago, and the fallout should have been fixed in 7d48278859cabcf0e08df27e1d5f839a1694fb1f

**Comment by carllerche** [comment]
Fixed on master

**Comment by posborne** [comment]
@fhartwig, Bah... Yep.  Wrong branch.
